/**
 * BunMail's runtime migration runner.
 *
 * Why this exists (and not `drizzle-kit push`):
 *   `drizzle-kit` parses the TypeScript schema files at runtime, which
 *   pulls esbuild's precompiled Go binary into the production Docker
 *   image. That binary's bundled Go stdlib racks up ~36 CVEs in our
 *   Trivy scan that aren't actually exploitable (esbuild doesn't accept
 *   untrusted network input) but constantly pollute the Security tab.
 *
 *   This runner is a 60-line replacement: it reads the static `.sql`
 *   files generated by `drizzle-kit generate` at dev/build time and
 *   applies them at runtime. drizzle-kit + esbuild stay in dev/CI only.
 *
 * Safety properties:
 *   - **Idempotent** — every applied migration is recorded in
 *     `__bunmail_migrations` keyed by `tag`; reruns are no-ops.
 *   - **Auto-baseline** — if the migrations table is empty but the
 *     schema's first table (`api_keys`) already exists, we infer this
 *     is a database originally provisioned by `db:push` and mark all
 *     known migrations as applied without running them. New migrations
 *     added after this point apply normally.
 *   - **Single-pass** — migrations apply in journal order; no
 *     concurrent runs (assumes a single replica per database, which is
 *     enforced today by the in-memory queue anyway, see #20).
 *   - **All-or-nothing per migration** — each SQL file runs inside a
 *     transaction; a failure mid-file rolls back and aborts the run.
 */

import { readFile } from "fs/promises";
import { join } from "path";
import { SQL } from "bun";
import { config } from "../config.ts";
import { logger } from "../utils/logger.ts";

const MIGRATIONS_DIR = join(import.meta.dir, "..", "..", "drizzle");
const MIGRATIONS_TABLE = "__bunmail_migrations";

interface JournalEntry {
  idx: number;
  tag: string;
}

interface Journal {
  entries: JournalEntry[];
}

/**
 * Loads the journal file produced by `drizzle-kit generate`. The journal
 * is the canonical order — file system listing order is not reliable
 * across platforms.
 */
async function loadJournal(): Promise<Journal> {
  const journalPath = join(MIGRATIONS_DIR, "meta", "_journal.json");
  const raw = await readFile(journalPath, "utf-8");
  return JSON.parse(raw) as Journal;
}

/**
 * Splits an SQL migration file into individual statements at the
 * `--> statement-breakpoint` markers Drizzle inserts. Each statement is
 * trimmed; empty fragments are dropped.
 */
function splitStatements(sql: string): string[] {
  return sql
    .split("--> statement-breakpoint")
    .map((s) => s.trim())
    .filter((s) => s.length > 0);
}

/**
 * Returns true when the database appears to have been populated by an
 * earlier `db:push` run (schema present, no migrations table). Used
 * once on first runner invocation to avoid re-running migrations
 * against a database that already has the resulting schema.
 */
async function isLegacySchema(sql: SQL): Promise<boolean> {
  /** Existence check on the canonical first table — pick something that's
   *  always part of an initialised BunMail DB. */
  const result = await sql<{ exists: boolean }[]>`
    SELECT to_regclass('public.api_keys') IS NOT NULL AS exists
  `;
  return result[0]?.exists === true;
}

/**
 * Runs every migration in the journal whose tag isn't already recorded
 * in `__bunmail_migrations`. Designed to be called once at container
 * start, before the HTTP listener starts accepting traffic.
 */
export async function runMigrations(databaseUrl?: string): Promise<{
  applied: string[];
  baselined: string[];
  alreadyApplied: string[];
}> {
  const sql = new SQL(databaseUrl ?? config.database.url);

  /** Bootstrap the migrations table itself if missing. */
  await sql`
    CREATE TABLE IF NOT EXISTS ${sql(MIGRATIONS_TABLE)} (
      tag         text PRIMARY KEY,
      applied_at  timestamptz NOT NULL DEFAULT now()
    )
  `;

  const journal = await loadJournal();
  const recorded = await sql<{ tag: string }[]>`
    SELECT tag FROM ${sql(MIGRATIONS_TABLE)}
  `;
  const recordedTags = new Set(recorded.map((r) => r.tag));

  const applied: string[] = [];
  const baselined: string[] = [];
  const alreadyApplied: string[] = [];

  /**
   * If the migrations table is empty but the schema is already there,
   * this database was provisioned by `db:push`. Record every existing
   * migration as already-applied so we don't re-run DDL and corrupt
   * existing data.
   */
  const shouldBaseline = recordedTags.size === 0 && (await isLegacySchema(sql));
  if (shouldBaseline) {
    logger.warn("Detected legacy db:push-provisioned schema; baselining migrations", {
      count: journal.entries.length,
    });
    for (const entry of journal.entries) {
      await sql`
        INSERT INTO ${sql(MIGRATIONS_TABLE)} (tag) VALUES (${entry.tag})
      `;
      baselined.push(entry.tag);
      recordedTags.add(entry.tag);
    }
  }

  for (const entry of journal.entries) {
    if (recordedTags.has(entry.tag)) {
      alreadyApplied.push(entry.tag);
      continue;
    }

    const filePath = join(MIGRATIONS_DIR, `${entry.tag}.sql`);
    const fileContents = await readFile(filePath, "utf-8");
    const statements = splitStatements(fileContents);

    logger.info("Applying migration", {
      tag: entry.tag,
      statements: statements.length,
    });

    /**
     * Apply all statements + record the migration row inside a single
     * transaction. If any statement fails, the whole migration rolls
     * back and the runner aborts — re-running picks up cleanly because
     * the migration row was never written.
     */
    await sql.begin(async (tx) => {
      for (const stmt of statements) {
        await tx.unsafe(stmt);
      }
      await tx`
        INSERT INTO ${tx(MIGRATIONS_TABLE)} (tag) VALUES (${entry.tag})
      `;
    });

    applied.push(entry.tag);
  }

  await sql.close();

  if (applied.length > 0) {
    logger.info("Migrations applied", { count: applied.length, tags: applied });
  } else if (baselined.length > 0) {
    logger.info("Schema baselined; no new migrations", {
      baselined: baselined.length,
    });
  } else {
    logger.info("No new migrations", { upToDate: alreadyApplied.length });
  }

  return { applied, baselined, alreadyApplied };
}

/**
 * Entry point when invoked directly: `bun run src/db/migrate.ts`.
 * The Dockerfile uses this in the run-stage CMD.
 */
if (import.meta.main) {
  try {
    await runMigrations();
    process.exit(0);
  } catch (err) {
    logger.error("Migration run failed", {
      error: err instanceof Error ? err.message : String(err),
    });
    process.exit(1);
  }
}
